apiVersion: v1
kind: Service
namespace: prod
metadata:
  name: py-app-prod
  labels: 
    app: py-prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: py-prod
  type: LoadBalancer

