apiVersion: v1
kind: Service
metadata:
  name: py-app
  labels: 
    app: py-one
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: py-one
  type: LoadBalancer

