
name: docker_build_push_acr_uat
on:
  workflow_dispatch:
  push:
    branch: [ "uat" ]
env:
  IMAGE_NAME: pyhello
  TAG: uat_v2
jobs:
  docker_build_push_acr:
    name: 'docker_build_push_acr_uat'
    runs-on: [self-hosted, Linux, X64, custrunner]

    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    # - name: Checkout
    #   uses: actions/checkout@v2
    #   # with:
    #   #   ref: main
    #   #   submodules: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # - name: Set up Docker Buildx
    #   id: buildx
    #   uses: docker/setup-buildx-action@v3

    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
        endpoint: builders

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:    
        login-server: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # - name: Build the frontend image and push it to ACR
    #   uses: docker/build-push-action@v2
    #   with:
    #     context:
    #     push: true
    #     tags: ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} #tamopsgithubacr.azurecr.io/aspcoresample:${{ github.sha }}
    #     file: Dockerfile
    #     #${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    - name: Update values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'manifests/prod/ndeploy.yml'
        #propertyPath: 'file.version'
        propertyPath: 'spec.template.spec.containers[0].image'
        value: ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        #value: ${{ env.TAG }}
        # commitChange: true
        branch: uat
        targetBranch: uat
        # masterBranchName: uat

    - run: |
           docker images
           docker ps
           docker build --no-cache -f Dockerfile . -t ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
           docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
